/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-12-27 23:33:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class meetingmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/BCLEFinal/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/viewpages/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1640611279472L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>B:CLE</title>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"css/main.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import\r\n");
      out.write("\turl('https://fonts.googleapis.com/css?family=Exo+2|Noto+Sans+KR&display=swap')\r\n");
      out.write("\t;\r\n");
      out.write("body {font-family: 'Noto Sans KR', sans-serif; font-size: 14px;}\r\n");
      out.write("/* .info {\r\n");
      out.write("\twidth: 100vh;\r\n");
      out.write("\theight: 30vh;\r\n");
      out.write("\tpadding : 5vh;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".ProfileInfo {\r\n");
      out.write("\twidth: 70vh;\r\n");
      out.write("\theight: 30vh;\r\n");
      out.write("\tmargin: 10vh 0vh 0vh 70vh;\r\n");
      out.write("} */\r\n");
      out.write(".info {\r\n");
      out.write("\theight: 80%;\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("\tpadding : 5vh;\r\n");
      out.write("}\r\n");
      out.write(".ProfileInfo {\r\n");
      out.write("padding : 5vh;\r\n");
      out.write("width: 30%;\r\n");
      out.write("background-color : #D9D9D9;\r\n");
      out.write("}\r\n");
      out.write(".upper {\r\n");
      out.write("\tmargin: 10vh 30vh 0vh 30vh;\r\n");
      out.write("\tposition: fix;\r\n");
      out.write("\theight: 60%;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("}\r\n");
      out.write(".nav{\r\n");
      out.write("margin:0vh 30vh 0vh 30vh;\r\n");
      out.write("color : #105b63;\r\n");
      out.write("font-size : 18px;\r\n");
      out.write("}\r\n");
      out.write(".nav-link {\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 0.5rem 3rem;\r\n");
      out.write("    color: #0d6efd;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".nav-tabs .nav-link {\r\n");
      out.write("    margin-bottom: -1px;\r\n");
      out.write("    background: 0 0;\r\n");
      out.write("    border: 1px solid transparent;\r\n");
      out.write("    border-top-left-radius: .25rem;\r\n");
      out.write("    border-top-right-radius: .25rem;\r\n");
      out.write("    color : #105b63;\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write("   list-style:none;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write(".info ul li{\r\n");
      out.write("margin : 0vh 0vh 2vh 0vh;\r\n");
      out.write("border-bottom : 1px dotted #D9D9D9;\r\n");
      out.write("}\r\n");
      out.write(".col-lg-4{\r\n");
      out.write("margin : 5vh 10vh 0vh 10vh;\r\n");
      out.write("}\r\n");
      out.write(".col-lg-4 p{\r\n");
      out.write("margin-left : 4vh;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"upper\">\r\n");
      out.write("\t\t<div class=info>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t<li>카테고리 대분류>소분류</li>\r\n");
      out.write("\t\t\t\t<li>동아리 타이틀</li>\r\n");
      out.write("\t\t\t\t\t\t<li>개설일</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>인원수</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>지역</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"ProfileInfo\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t  <svg class=\"bd-placeholder-img rounded-circle\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: 140x140\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"#777\"/><text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\">140x140</text></svg>\r\n");
      out.write("\t  \r\n");
      out.write("\t\t\t  <p style= \"font-size : 20px;\">닉네임</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<div class=\"nav nav-tabs\" id=\"nav-tab\" role=\"tablist\">\r\n");
      out.write("\t\t\t<a class=\"nav-item nav-link active\" id=\"nav-home-tab\" data-toggle=\"tab\" href=\"#nav-home\" role=\"tab\"\r\n");
      out.write("\t\t\t\taria-controls=\"nav-home\" aria-selected=\"true\">기본정보</a> \r\n");
      out.write("\t\t\t\t<a class=\"nav-item nav-link\" \r\n");
      out.write("\t\t\t\tid=\"nav-profile-tab\" data-toggle=\"tab\"\r\n");
      out.write("\t\t\t\thref=\"beecalendarlist.action\" role=\"tab\" aria-controls=\"nav-profile\"\r\n");
      out.write("\t\t\t\taria-selected=\"false\">캘린더</a> \r\n");
      out.write("\t\t\t\t<a class=\"nav-item nav-link\"\r\n");
      out.write("\t\t\t\tid=\"nav-contact-tab\" data-toggle=\"tab\" href=\"#nav-contact\"\r\n");
      out.write("\t\t\t\trole=\"tab\" aria-controls=\"nav-contact\" aria-selected=\"false\">게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"nav-item nav-link\"\r\n");
      out.write("\t\t\t\tid=\"nav-contact-tab\" data-toggle=\"tab\" href=\"#nav-contact\"\r\n");
      out.write("\t\t\t\trole=\"tab\" aria-controls=\"nav-contact\" aria-selected=\"false\">회계</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"nav-item nav-link\"\r\n");
      out.write("\t\t\t\tid=\"nav-contact-tab\" data-toggle=\"tab\" href=\"#nav-contact\"\r\n");
      out.write("\t\t\t\trole=\"tab\" aria-controls=\"nav-contact\" aria-selected=\"false\">사진첩</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"nav-item nav-link\"\r\n");
      out.write("\t\t\t\tid=\"nav-contact-tab\" data-toggle=\"tab\" href=\"#nav-contact\"\r\n");
      out.write("\t\t\t\trole=\"tab\" aria-controls=\"nav-contact\" aria-selected=\"false\">회의</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"nav-item nav-link\"\r\n");
      out.write("\t\t\t\tid=\"nav-contact-tab\" data-toggle=\"tab\" href=\"#nav-contact\"\r\n");
      out.write("\t\t\t\trole=\"tab\" aria-controls=\"nav-contact\" aria-selected=\"false\">결산</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$('#myTab a').on('click', function (e) {\r\n");
      out.write("\t\t  e.preventDefault()\r\n");
      out.write("\t\t  $(this).tab('show')\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
