/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-12-27 15:00:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BoardFreeBulletinList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/BCLEFinal/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/viewpages/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1640611279472L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    request.setCharacterEncoding("UTF-8");
    String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>BoardFreeBulletinList.jsp</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- \r\n");
      out.write(" - BoardFreeBulletinList.jsp\r\n");
      out.write("-  대표게시판-자유글(메인)\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<!-- 네브 영역 -->\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 메뉴 영역 -->\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 콘텐츠 영역 -->\r\n");
      out.write("\t\t<div id=\"content\" style=\"margin-left: 30vh;\">\r\n");
      out.write("\t\t\t<h1>[ 자유글 ]</h1>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t\t<!-- 스토리보드에 셀박있는데 필요없을듯. -->\r\n");
      out.write("\t\t\t\t\t<!-- <select>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"전체\" selected=\"selected\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"제목\" >전체</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"전체\" >전체</option>\r\n");
      out.write("\t\t\t\t\t</select> -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" value=\"검색어입력\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"검색\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table id=\"BoardFreeBulletinList\" class=\"table\" >\r\n");
      out.write("\t \t\t \t<tr>\r\n");
      out.write("\t \t\t \t\t<!-- 항목 7EA --> \r\n");
      out.write("\t \t\t \t\t<th>순번</th>\r\n");
      out.write("\t \t\t \t\t<th>글제목</th>\r\n");
      out.write("\t \t\t \t\t<th>닉네임</th>\r\n");
      out.write("\t \t\t \t\t<th>작성일</th>\t\t \t\t\t \t\t\r\n");
      out.write("\t \t\t \t\t<th>댓글수</th>\t\t \t\t\t \t\t\r\n");
      out.write("\t \t\t \t\t<th>조회수</th>\t\r\n");
      out.write("\t \t\t \t\t<th></th> \t\t\r\n");
      out.write("\t \t\t \t</tr>\r\n");
      out.write("\t \t\t \t\r\n");
      out.write("\t \t\t \t<tr> \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>1099</td>\r\n");
      out.write("\t \t\t \t\t<td>함께달려요~~~!!달리자!</td> \r\n");
      out.write("\t \t\t \t\t<td>성수동불주먹</td>\r\n");
      out.write("\t \t\t \t\t<td>2021.12.15</td>\r\n");
      out.write("\t \t\t \t\t<td>3</td>\r\n");
      out.write("\t \t\t \t\t<td>11</td>\r\n");
      out.write("\t \t\t \t\t<td><input type=\"button\" value=\"신고\"></td>\r\n");
      out.write("\t \t\t \t</tr>\r\n");
      out.write("\t \t\t \t<tr> \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>1098</td>\r\n");
      out.write("\t \t\t \t\t<td>야구보러가는사람?</td> \r\n");
      out.write("\t \t\t \t\t<td>나는야도깨비</td>\r\n");
      out.write("\t \t\t \t\t<td>2021.12.05</td>\r\n");
      out.write("\t \t\t \t\t<td>10</td>\r\n");
      out.write("\t \t\t \t\t<td>20</td>\r\n");
      out.write("\t \t\t \t\t<td><input type=\"button\" value=\"신고\"></td>\r\n");
      out.write("\t \t\t \t</tr>\r\n");
      out.write("\t \t\t \t<tr> \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>1097</td>\r\n");
      out.write("\t \t\t \t\t<td>맛난디저트 만들어봤어여</td> \t \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>성수동불주먹</td>\r\n");
      out.write("\t \t\t \t\t<td>2021.12.05</td>\r\n");
      out.write("\t \t\t \t\t<td>3</td>\r\n");
      out.write("\t \t\t \t\t<td>53</td>\r\n");
      out.write("\t \t\t \t\t<td><input type=\"button\" value=\"신고\"></td>\r\n");
      out.write("\t \t\t \t</tr>\r\n");
      out.write("\t \t\t \t<tr> \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>1096</td>\r\n");
      out.write("\t \t\t \t\t<td>영화관람동아리 같이들어갈사람</td> \t \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>보노보노</td>\r\n");
      out.write("\t \t\t \t\t<td>2021.11.25</td>\r\n");
      out.write("\t \t\t \t\t<td>2</td>\r\n");
      out.write("\t \t\t \t\t<td>33</td>\r\n");
      out.write("\t \t\t \t\t<td><input type=\"button\" value=\"신고\"></td>\r\n");
      out.write("\t \t\t \t</tr>\r\n");
      out.write("\t \t\t \t<tr> \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>1095</td>\r\n");
      out.write("\t \t\t \t\t<td>자유게시판 첨이네요</td> \t \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>포로리</td>\r\n");
      out.write("\t \t\t \t\t<td>2021.11.05</td>\r\n");
      out.write("\t \t\t \t\t<td>0</td>\r\n");
      out.write("\t \t\t \t\t<td>5</td>\r\n");
      out.write("\t \t\t \t\t<td><input type=\"button\" value=\"신고\"></td>\r\n");
      out.write("\t \t\t \t</tr>\r\n");
      out.write("\t \t\t \t<tr> \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>1094</td>\r\n");
      out.write("\t \t\t \t\t<td>런닝메이트구합니당</td> \t \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>방가방가</td>\r\n");
      out.write("\t \t\t \t\t<td>2021.10.15</td>\r\n");
      out.write("\t \t\t \t\t<td>1</td>\r\n");
      out.write("\t \t\t \t\t<td>32</td>\r\n");
      out.write("\t \t\t \t\t<td><input type=\"button\" value=\"신고\"></td>\r\n");
      out.write("\t \t\t \t</tr>\r\n");
      out.write("\t \t\t \t<tr> \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>1093</td>\r\n");
      out.write("\t \t\t \t\t<td>이 뮤지컬너무잼잼잼</td> \t \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>햄토리</td>\r\n");
      out.write("\t \t\t \t\t<td>2021.10.01</td>\r\n");
      out.write("\t \t\t \t\t<td>2</td>\r\n");
      out.write("\t \t\t \t\t<td>62</td>\r\n");
      out.write("\t \t\t \t\t<td><input type=\"button\" value=\"신고\"></td>\r\n");
      out.write("\t \t\t \t</tr>\r\n");
      out.write("\t \t\t \t<tr> \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>1092</td>\r\n");
      out.write("\t \t\t \t\t<td>인스타감성카페투어햇어용</td>\t \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>빨간망토</td> \r\n");
      out.write("\t \t\t \t\t<td>2021.10.01</td>\r\n");
      out.write("\t \t\t \t\t<td>2</td>\r\n");
      out.write("\t \t\t \t\t<td>31</td>\r\n");
      out.write("\t \t\t \t\t<td><input type=\"button\" value=\"신고\"></td>\r\n");
      out.write("\t \t\t \t</tr>\r\n");
      out.write("\t \t\t \t<tr> \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>1091</td>\r\n");
      out.write("\t \t\t \t\t<td>공방체험해봄</td> \t \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>차차</td>\r\n");
      out.write("\t \t\t \t\t<td>2021.09.25</td>\r\n");
      out.write("\t \t\t \t\t<td>3</td>\r\n");
      out.write("\t \t\t \t\t<td>30</td>\r\n");
      out.write("\t \t\t \t\t<td><input type=\"button\" value=\"신고\"></td>\r\n");
      out.write("\t \t\t \t</tr>\r\n");
      out.write("\t \t\t \t<tr> \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>1090</td>\r\n");
      out.write("\t \t\t \t\t<td>영화보는게 제일조아!!!</td> \t \t\t \t\t\r\n");
      out.write("\t \t\t \t\t<td>영화덕후</td>\r\n");
      out.write("\t \t\t \t\t<td>2021.09.05</td>\r\n");
      out.write("\t \t\t \t\t<td>0</td>\r\n");
      out.write("\t \t\t \t\t<td>46</td>\r\n");
      out.write("\t \t\t \t\t<td><input type=\"button\" value=\"신고\"></td>\r\n");
      out.write("\t \t\t \t</tr>\r\n");
      out.write(" \t\t \t</table>\r\n");
      out.write(" \t\t \t\r\n");
      out.write(" \t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t<p>1 Prev 21 22 23 24 25 26 27 28 29 30 Next 54</p>\t\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write(" \t\t \t\r\n");
      out.write(" \t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t <!-- 풋터영역 -->\r\n");
      out.write("\t     <div>\r\n");
      out.write("\t      \t");
      if (_jspx_meth_c_005fimport_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t     </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/view/BoardFreeBulletinList.jsp(23,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/nav.action");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/view/BoardFreeBulletinList.jsp(29,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("mainSideTab.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f2 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f2_reused = false;
    try {
      _jspx_th_c_005fimport_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f2.setParent(null);
      // /WEB-INF/view/BoardFreeBulletinList.jsp(168,8) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setUrl("footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f2 = _jspx_th_c_005fimport_005f2.doStartTag();
        if (_jspx_th_c_005fimport_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f2);
      _jspx_th_c_005fimport_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f2_reused);
    }
    return false;
  }
}
