/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-12-27 18:01:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/BCLEFinal/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/viewpages/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1640611279472L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    request.setCharacterEncoding("UTF-8");
    String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Join.jsp</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(cp);
      out.write("/js/util.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/* .outer {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center; \r\n");
      out.write("  flex-direction: row; \r\n");
      out.write("  justify-content: center; \r\n");
      out.write("}\r\n");
      out.write(".inner {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translate(-50%,-50%);\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write(".outer\r\n");
      out.write("{\r\n");
      out.write("   border: 1px solid #ccc;\r\n");
      out.write("   border-radius: 5px;\r\n");
      out.write("   width: 100vh;\r\n");
      out.write("   padding: 50px;\r\n");
      out.write("   margin: 5vh 50vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function()   // 페이지가 로드됐을 때 제이쿼리 실행?\r\n");
      out.write("{\r\n");
      out.write("   \r\n");
      out.write("   $(\"#emailText\").focusout(function()\r\n");
      out.write("   {\r\n");
      out.write("      if(!isValidEmail($(\"#emailText\").val()))\r\n");
      out.write("         {\r\n");
      out.write("            $(\"#emailText\").val(\"\");\r\n");
      out.write("            $(\"#e_msg\").html('이메일 형식에 맞지 않습니다.');\r\n");
      out.write("            $(\"#e_msg\").css(\"display\",\"inline\");\r\n");
      out.write("            return;\r\n");
      out.write("         }\r\n");
      out.write("         else\r\n");
      out.write("         {\r\n");
      out.write("            $(\"#e_msg\").html('');\r\n");
      out.write("         \r\n");
      out.write("         }\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   // 지역 같은값 중복 방지\r\n");
      out.write("   $(\"#region_S_Id2\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      if( $(\"#region_S_Id2\").val() == $(\"#region_S_Id1\").val())\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"이미 선택하신 지역 입니다.\");\r\n");
      out.write("         $('#region_S_Id2').val('');\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   $(\"#region_S_Id3\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      if( $(\"#region_S_Id3\").val() == $(\"#region_S_Id1\").val() || $(\"#region_S_Id3\").val() == $(\"#region_S_Id2\").val())\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"이미 선택하신 지역 입니다.\");\r\n");
      out.write("         $('#region_S_Id3').val('');\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   // 카테고리 같은값 중복 방지\r\n");
      out.write("   $(\"#category_S_Id2\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      //alert(\"이미 선택하신 카테고리 입니다.\");\r\n");
      out.write("      if( $(\"#category_S_Id2\").val() == $(\"#category_S_Id1\").val())\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"이미 선택하신 카테고리 입니다.\");\r\n");
      out.write("         $('#category_L_Id2').val('');\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   $(\"#category_S_Id3\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      if( $(\"#category_S_Id3\").val() == $(\"#category_S_Id2\").val() || $(\"#category_S_Id3\").val() == $(\"#category_S_Id1\").val())\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"이미 선택하신 카테고리 입니다.\");\r\n");
      out.write("         $('#category_S_Id3').val('');\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   $(\"#category_S_Id4\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      if( $(\"#category_S_Id4\").val() == $(\"#category_S_Id3\").val() || $(\"#category_S_Id4\").val() == $(\"#category_S_Id2\").val()\r\n");
      out.write("            || $(\"#category_S_Id4\").val() == $(\"#category_S_Id1\").val())\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"이미 선택하신 카테고리 입니다.\");\r\n");
      out.write("         $('#category_S_Id4').val('');\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   $(\"#category_S_Id5\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      if( $(\"#category_S_Id5\").val() == $(\"#category_S_Id4\").val() || $(\"#category_S_Id5\").val() == $(\"#category_S_Id3\").val()\r\n");
      out.write("            || $(\"#category_S_Id5\").val() == $(\"#category_S_Id2\").val() || $(\"#category_S_Id5\").val() == $(\"#category_S_Id1\").val())\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"이미 선택하신 카테고리 입니다.\");\r\n");
      out.write("         $('#category_S_Id5').val('');\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   // 주민번호 유효성 검사\r\n");
      out.write("   $(\"#ssn2\").focusout(function()\r\n");
      out.write("    {\r\n");
      out.write("    let ssn = $(\"#ssn1\").val()+$(\"#ssn2\").val();\r\n");
      out.write("    \r\n");
      out.write("    //alert(ssn);\r\n");
      out.write("    \r\n");
      out.write("    $.ajax({\r\n");
      out.write("       url : \"ssncheck.action\"\r\n");
      out.write("       ,type : \"POST\"\r\n");
      out.write("       ,data : {ssn:ssn}\r\n");
      out.write("       ,dataType:\"json\"\r\n");
      out.write("       ,success:function(result)\r\n");
      out.write("       {\r\n");
      out.write("          //alert(\"testtest\");\r\n");
      out.write("          if(result.checkSsn==0)\r\n");
      out.write("          {\r\n");
      out.write("             alert(\"사용중인 계정입니다.\");\r\n");
      out.write("             //$(\"#ssn1\").val(\"\");\r\n");
      out.write("             //$(\"#ssn2\").val(\"\");\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("       }\r\n");
      out.write("       , error:function(e)\r\n");
      out.write("       {\r\n");
      out.write("          alert(e.responseText);\r\n");
      out.write("       }\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("   })\r\n");
      out.write("    \r\n");
      out.write("    //var result = \"\";\r\n");
      out.write("    //alert(\"test\");\r\n");
      out.write("    $(\"#pwd\").focusout(function()\r\n");
      out.write("    {\r\n");
      out.write("       $(\"#p_msg1\").html('');\r\n");
      out.write("       if($(\"#pwd\").val()==\"\")\r\n");
      out.write("       {\r\n");
      out.write("          $(\"#p_msg1\").html('');\r\n");
      out.write("       }\r\n");
      out.write("       else if(!isPassword($(\"#pwd\").val()) )\r\n");
      out.write("       {   \r\n");
      out.write("          $(\"#p_msg1\").html('특수문자을 포함한 숫자, 영어 포함 8~16자를 입력해야 합니다.');\r\n");
      out.write("          $(\"#p_msg1\").css(\"display\", \"inline\");\r\n");
      out.write("          $(\"#pwd\").val(\"\");\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // 비밀번호 확인\r\n");
      out.write("    $(\"#pwd2\").focusout(function()\r\n");
      out.write("    {\r\n");
      out.write("       \r\n");
      out.write("       if((event.keyCode < 48) || (event.keyCode > 57)) \r\n");
      out.write("       {\r\n");
      out.write("          if(navigator.appName==\"Netscape\")\r\n");
      out.write("             event.preventDefault();\r\n");
      out.write("          else\r\n");
      out.write("             event.returnValue = false;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       //alert(\"test\");\r\n");
      out.write("       //alert($(\"#pwd\").val() + \":\" + $(\"#pwd2\").val());\r\n");
      out.write("       $(\"#p_msg1\").html('');\r\n");
      out.write("       if($(\"#pwd2\").val()==\"\")\r\n");
      out.write("       {\r\n");
      out.write("          $(\"#p_msg2\").html('');\r\n");
      out.write("       }\r\n");
      out.write("       else if($(\"#pwd\").val()==$(\"#pwd2\").val()&&$(\"#pwd\"))\r\n");
      out.write("       {\r\n");
      out.write("             \r\n");
      out.write("          $(\"#p_msg2\").html('비밀번호가 일치합니다.');\r\n");
      out.write("          $(\"#p_msg2\").css(\"display\", \"inline\");\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       else\r\n");
      out.write("       {\r\n");
      out.write("          \r\n");
      out.write("          $(\"#p_msg2\").html('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("          $(\"#p_msg2\").css(\"display\", \"inline\");\r\n");
      out.write("          $(\"#pwd2\").val(\"\");\r\n");
      out.write("          //$(\"#pwd2\").val()=\"\";\r\n");
      out.write("       }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // 비밀번호 1과 2 입력후 1을 바꿨을때도 비밀번호 유효성검사 적용되게 하기 위해서 쓴 부분\r\n");
      out.write("    $(\"#pwd\").focusout(function()\r\n");
      out.write("    {\r\n");
      out.write("       \r\n");
      out.write("       if((event.keyCode < 48) || (event.keyCode > 57)) \r\n");
      out.write("       {\r\n");
      out.write("          if(navigator.appName==\"Netscape\")\r\n");
      out.write("             event.preventDefault();\r\n");
      out.write("          else\r\n");
      out.write("             event.returnValue = false;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       if($(\"#pwd2\").val()==\"\")\r\n");
      out.write("       {\r\n");
      out.write("          $(\"#p_msg2\").html('');\r\n");
      out.write("       }\r\n");
      out.write("       else if($(\"#pwd\").val()==$(\"#pwd2\").val()&&$(\"#pwd\"))\r\n");
      out.write("       {\r\n");
      out.write("             \r\n");
      out.write("          $(\"#p_msg2\").html('비밀번호가 일치합니다.');\r\n");
      out.write("          $(\"#p_msg2\").css(\"display\", \"inline\");\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       else\r\n");
      out.write("       {\r\n");
      out.write("          \r\n");
      out.write("          $(\"#p_msg2\").html('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("          $(\"#p_msg2\").css(\"display\", \"inline\");\r\n");
      out.write("          //$(\"#pwd2\").val(\"\");\r\n");
      out.write("          //$(\"#pwd2\").val()=\"\";\r\n");
      out.write("       }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\"#tel1\").focusout(function()\r\n");
      out.write("    {\r\n");
      out.write("       \r\n");
      out.write("       $(\"#t_msg\").html('');\r\n");
      out.write("       if($(\"#tel1\").val()==\"\")\r\n");
      out.write("       {\r\n");
      out.write("          $(\"#t_msg2\").html('');\r\n");
      out.write("       }\r\n");
      out.write("       else if(!isValidPhone($(\"#tel1\").val()) )\r\n");
      out.write("       {\r\n");
      out.write("          $(\"#t_msg\").html(\"잘못된 연락처 형식입니다. '-' 포함해서 입력해주세요.\");\r\n");
      out.write("          $(\"#t_msg\").css(\"display\", \"inline\");\r\n");
      out.write("          $(\"#tel1\").val(\"\");\r\n");
      out.write("       }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    $(\"#ssn2\").focusout(function()\r\n");
      out.write("    {   \r\n");
      out.write("       $(\"#s_msg\").html('');\r\n");
      out.write("       if(!isValidResidentNO($(\"#ssn1\").val(),$(\"#ssn2\").val()) && $(\"#ssn2\").val().length == 0)\r\n");
      out.write("       {   \r\n");
      out.write("          $(\"#s_msg\").html(\"잘못된 주민번호입니다.\");\r\n");
      out.write("          $(\"#s_msg\").css(\"display\", \"inline\");\r\n");
      out.write("          $(\"#s_msg\").css('color', 'red');\r\n");
      out.write("          $(\"#ssn2\").val(\"\");\r\n");
      out.write("          $(\"#ssn1\").val(\"\");\r\n");
      out.write("       }\r\n");
      out.write("      \r\n");
      out.write("       else\r\n");
      out.write("       {\r\n");
      out.write("          $(\"#s_msg\").html(\"올바른 주민번호입니다.\");\r\n");
      out.write("          $(\"#s_msg\").css(\"display\", \"inline\");\r\n");
      out.write("          $(\"#s_msg\").css('color', 'green');\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // 주민번호 1 / 2 둘다  입력 후 1을 변경했을때도 유효성검사 하도록하는 구문\r\n");
      out.write("    $(\"#ssn1\").focusout(function()\r\n");
      out.write("    {   \r\n");
      out.write("       //$(\"#s_msg\").html('');\r\n");
      out.write("       if($(\"#ssn2\").val().length != 0 && !isValidResidentNO($(\"#ssn1\").val(),$(\"#ssn2\").val()))\r\n");
      out.write("       {   \r\n");
      out.write("          $(\"#s_msg\").html(\"잘못된 주민번호입니다.\");\r\n");
      out.write("          $(\"#s_msg\").css(\"display\", \"inline\");\r\n");
      out.write("          $(\"#s_msg\").css('color', 'red');\r\n");
      out.write("          $(\"#ssn2\").val(\"\");\r\n");
      out.write("          $(\"#ssn1\").val(\"\");\r\n");
      out.write("       }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   //각 상황별 alert 창 → required로 했는데 클리어하지가 않아서, 각 상황에 맞게 알림창을 띄우기로했다.\r\n");
      out.write("   $(\"#submitBtn\").click(function()\r\n");
      out.write("   {\r\n");
      out.write("      //alert($(\"#file\").val().length);\r\n");
      out.write("      \r\n");
      out.write("      if ($(\"#file\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"사진을 등록해주세요.\");\r\n");
      out.write("         $(\"#file\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ($(\"#name\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"이름을 입력해주세요.\");\r\n");
      out.write("         $(\"#name\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ($(\"#userId\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("         $(\"#userId\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ($(\"#emailText\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"이메일을 입력해주세요.\");\r\n");
      out.write("         $(\"#emailText\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ($(\"#pwd\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("         $(\"#pwd\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ($(\"#pwd2\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"비밀번호를 다시 입력해주세요.\");\r\n");
      out.write("         $(\"#pwd2\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ($(\"#ssn1\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"주민번호 앞자리를 입력해주세요.\");\r\n");
      out.write("         $(\"#ssn1\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ($(\"#ssn2\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"주민번호 뒷자리를 입력해주세요.\");\r\n");
      out.write("         $(\"#ssn2\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ($(\"#tel1\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"연락처를 입력하세요.\");\r\n");
      out.write("         $(\"#tel1\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ($(\"#nickName\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"닉네임을 입력하세요.\");\r\n");
      out.write("         $(\"#nickName\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      if ($(\"#region_S_Id1\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"지역은 1개까지 필수 입력사항입니다.\");\r\n");
      out.write("         $(\"#region_S_Id1\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      if ($(\"#category_L_Id1\").val().length == 0)\r\n");
      out.write("      {\r\n");
      out.write("         alert(\"카테고리는 1개까지 필수 입력사항입니다.\");\r\n");
      out.write("         $(\"#category_L_Id1\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      $(\"#joinForm\").submit();\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   // 아이디 중복 검사\r\n");
      out.write("   //alert(\"test\");\r\n");
      out.write("   $('.input_id').keyup(function()\r\n");
      out.write("   {\r\n");
      out.write("      let userId = $('.input_id').val();   \r\n");
      out.write("      \r\n");
      out.write("      //alert(userId);\r\n");
      out.write("      \r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url : \"checkid.action\"\r\n");
      out.write("         , type : \"POST\"\r\n");
      out.write("         , data : {userId : userId}\r\n");
      out.write("         , dataType : \"json\"      // check~!!!\r\n");
      out.write("         , success : function(result)\r\n");
      out.write("         {\r\n");
      out.write("            if(result.checkId == 0){\r\n");
      out.write("               //alert(result.checkId);\r\n");
      out.write("               //alert(\"사용할 수 없는 아이디\");\r\n");
      out.write("               $(\"#checkId\").html('사용할 수 없는 아이디입니다.');\r\n");
      out.write("               $(\"#checkId\").css('color', 'red');\r\n");
      out.write("               $('#userId').val('');   // 사용할 수 없으면 빈칸으로 만들기\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("               //alert(result.checkId);\r\n");
      out.write("               //alert(\"사용할 수 있는 아이디\");\r\n");
      out.write("               $(\"#checkId\").html('사용할 수 있는 아이디입니다.');\r\n");
      out.write("               $(\"#checkId\").css('color', 'green');\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         , error : function(e)\r\n");
      out.write("         {\r\n");
      out.write("            alert(e.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   // 닉네임 중복 검사\r\n");
      out.write("   $('.input_nickname').keyup(function()\r\n");
      out.write("   {\r\n");
      out.write("      let nickname = $('.input_nickname').val();   \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url : \"checknickname.action\"\r\n");
      out.write("         , type : \"POST\"\r\n");
      out.write("         , data : {nickname : nickname}\r\n");
      out.write("         , dataType : \"json\"      \r\n");
      out.write("         , success : function(result)\r\n");
      out.write("         {\r\n");
      out.write("            if(result.checkNickName == 0){\r\n");
      out.write("               $(\"#checkNickName\").html('사용할 수 없는 닉네임입니다.');\r\n");
      out.write("               $(\"#checkNickName\").css('color', 'red');\r\n");
      out.write("               $('.input_nickname').val('');\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("               $(\"#checkNickName\").html('사용할 수 있는 닉네임입니다.');\r\n");
      out.write("               $(\"#checkNickName\").css('color', 'green');\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         , error : function(e)\r\n");
      out.write("         {\r\n");
      out.write("            alert(e.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   // 이름 한글만 되도록 하는 정규식 유효성 검사\r\n");
      out.write("   $('#name').keypress(function onlyHangul() \r\n");
      out.write("   {\r\n");
      out.write("      if((event.keyCode < 12592) || (event.keyCode > 12687)) \r\n");
      out.write("      {\r\n");
      out.write("         if(navigator.appName==\"Netscape\")\r\n");
      out.write("         {\r\n");
      out.write("            event.preventDefault();\r\n");
      out.write("            alert(\"한글만 입력할 수 있습니다!!\");\r\n");
      out.write("         }\r\n");
      out.write("         else\r\n");
      out.write("            event.returnValue = false;\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   // 지역 대분류 → 소분류 선택 - 1\r\n");
      out.write("   $(\"#region_L_Id1\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      //alert('변경');\r\n");
      out.write("      //alert($(\"#region_L_Id\").val());\r\n");
      out.write("      \r\n");
      out.write("      $.ajax(\r\n");
      out.write("      {\r\n");
      out.write("         type : \"POST\"\r\n");
      out.write("         ,url : \"ajaxjoinregion.action\"\r\n");
      out.write("         ,data : {region_L_Id : $(\"#region_L_Id1\").val()}\r\n");
      out.write("         ,dataType : \"json\"\r\n");
      out.write("         ,success : function(result)\r\n");
      out.write("         {\r\n");
      out.write("            //alert(result);\r\n");
      out.write("            $(\"#region_S_Id1\").children().remove();\r\n");
      out.write("            $(\"#region_S_Id1\").append(\"<option value=\\\"\\\">선택</option>\");\r\n");
      out.write("            \r\n");
      out.write("            for(var i=0; i<result.length; i++)\r\n");
      out.write("            {\r\n");
      out.write("               $(\"#region_S_Id1\").append(\"<option value=\\\"\"+result[i].region_s_id+\"\\\">\"+result[i].local+\"</option>\");\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         ,error : function(e)\r\n");
      out.write("         {\r\n");
      out.write("            alert(e.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      \r\n");
      out.write("       });\r\n");
      out.write("   \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   // 지역 대분류 → 소분류 선택 - 2\r\n");
      out.write("   $(\"#region_L_Id2\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      //alert('변경');\r\n");
      out.write("      //alert($(\"#region_L_Id\").val());\r\n");
      out.write("      \r\n");
      out.write("      $.ajax(\r\n");
      out.write("      {\r\n");
      out.write("         type : \"POST\"\r\n");
      out.write("         ,url : \"ajaxjoinregion.action\"\r\n");
      out.write("         ,data : {region_L_Id : $(\"#region_L_Id2\").val()}\r\n");
      out.write("         ,dataType : \"json\"\r\n");
      out.write("         ,success : function(result)\r\n");
      out.write("         {\r\n");
      out.write("            //alert(result);\r\n");
      out.write("            $(\"#region_S_Id2\").children().remove();\r\n");
      out.write("            $(\"#region_S_Id2\").append(\"<option value=\\\"\\\">선택</option>\");\r\n");
      out.write("            \r\n");
      out.write("            for(var i=0; i<result.length; i++)\r\n");
      out.write("            {\r\n");
      out.write("               $(\"#region_S_Id2\").append(\"<option value=\\\"\"+result[i].region_s_id+\"\\\">\"+result[i].local+\"</option>\");\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         ,error : function(e)\r\n");
      out.write("         {\r\n");
      out.write("            alert(e.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      \r\n");
      out.write("       });\r\n");
      out.write("   \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   // 지역 대분류 → 소분류 선택 - 3\r\n");
      out.write("   $(\"#region_L_Id3\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      //alert('변경');\r\n");
      out.write("      //alert($(\"#region_L_Id\").val());\r\n");
      out.write("      \r\n");
      out.write("      $.ajax(\r\n");
      out.write("      {\r\n");
      out.write("         type : \"POST\"\r\n");
      out.write("         ,url : \"ajaxjoinregion.action\"\r\n");
      out.write("         ,data : {region_L_Id : $(\"#region_L_Id3\").val()}\r\n");
      out.write("         ,dataType : \"json\"\r\n");
      out.write("         ,success : function(result)\r\n");
      out.write("         {\r\n");
      out.write("            //alert(result);\r\n");
      out.write("            $(\"#region_S_Id3\").children().remove();\r\n");
      out.write("            $(\"#region_S_Id3\").append(\"<option value=\\\"\\\">선택</option>\");\r\n");
      out.write("            \r\n");
      out.write("            for(var i=0; i<result.length; i++)\r\n");
      out.write("            {\r\n");
      out.write("               $(\"#region_S_Id3\").append(\"<option value=\\\"\"+result[i].region_s_id+\"\\\">\"+result[i].local+\"</option>\");\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         ,error : function(e)\r\n");
      out.write("         {\r\n");
      out.write("            alert(e.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      \r\n");
      out.write("       });\r\n");
      out.write("   \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   // 카테고리 대분류 → 소분류 선택 - 1\r\n");
      out.write("   $(\"#category_L_Id1\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      $.ajax(\r\n");
      out.write("      {\r\n");
      out.write("         type : \"POST\"\r\n");
      out.write("         ,url : \"ajaxjoincategory.action\"\r\n");
      out.write("         ,data : {category_L_Id : $(\"#category_L_Id1\").val()}\r\n");
      out.write("         ,dataType : \"json\"\r\n");
      out.write("         ,success : function(result)\r\n");
      out.write("         {\r\n");
      out.write("            //alert(result);\r\n");
      out.write("            $(\"#category_S_Id1\").children().remove();\r\n");
      out.write("            $(\"#category_S_Id1\").append(\"<option value=\\\"\\\">선택</option>\");\r\n");
      out.write("            \r\n");
      out.write("            for(var i=0; i<result.length; i++)\r\n");
      out.write("            {\r\n");
      out.write("               $(\"#category_S_Id1\").append(\"<option value=\\\"\"+result[i].category_s_id+\"\\\">\"+result[i].s_cat+\"</option>\");\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         ,error : function(e)\r\n");
      out.write("         {\r\n");
      out.write("            alert(e.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      \r\n");
      out.write("       });\r\n");
      out.write("   \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   // 카테고리 대분류 → 소분류 선택 - 2\r\n");
      out.write("   $(\"#category_L_Id2\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      $.ajax(\r\n");
      out.write("      {\r\n");
      out.write("         type : \"POST\"\r\n");
      out.write("         ,url : \"ajaxjoincategory.action\"\r\n");
      out.write("         ,data : {category_L_Id : $(\"#category_L_Id2\").val()}\r\n");
      out.write("         ,dataType : \"json\"\r\n");
      out.write("         ,success : function(result)\r\n");
      out.write("         {\r\n");
      out.write("            //alert(result);\r\n");
      out.write("            $(\"#category_S_Id2\").children().remove();\r\n");
      out.write("            $(\"#category_S_Id2\").append(\"<option value=\\\"\\\">선택</option>\");\r\n");
      out.write("            \r\n");
      out.write("            for(var i=0; i<result.length; i++)\r\n");
      out.write("            {\r\n");
      out.write("               $(\"#category_S_Id2\").append(\"<option value=\\\"\"+result[i].category_s_id+\"\\\">\"+result[i].s_cat+\"</option>\");\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         ,error : function(e)\r\n");
      out.write("         {\r\n");
      out.write("            alert(e.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      \r\n");
      out.write("       });\r\n");
      out.write("   \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   // 카테고리 대분류 → 소분류 선택 - 3\r\n");
      out.write("   $(\"#category_L_Id3\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      $.ajax(\r\n");
      out.write("      {\r\n");
      out.write("         type : \"POST\"\r\n");
      out.write("         ,url : \"ajaxjoincategory.action\"\r\n");
      out.write("         ,data : {category_L_Id : $(\"#category_L_Id3\").val()}\r\n");
      out.write("         ,dataType : \"json\"\r\n");
      out.write("         ,success : function(result)\r\n");
      out.write("         {\r\n");
      out.write("            //alert(result);\r\n");
      out.write("            $(\"#category_S_Id3\").children().remove();\r\n");
      out.write("            $(\"#category_S_Id3\").append(\"<option value=\\\"\\\">선택</option>\");\r\n");
      out.write("            \r\n");
      out.write("            for(var i=0; i<result.length; i++)\r\n");
      out.write("            {\r\n");
      out.write("               $(\"#category_S_Id3\").append(\"<option value=\\\"\"+result[i].category_s_id+\"\\\">\"+result[i].s_cat+\"</option>\");\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         ,error : function(e)\r\n");
      out.write("         {\r\n");
      out.write("            alert(e.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      \r\n");
      out.write("       });\r\n");
      out.write("   \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   // 카테고리 대분류 → 소분류 선택 - 4\r\n");
      out.write("   $(\"#category_L_Id4\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      $.ajax(\r\n");
      out.write("      {\r\n");
      out.write("         type : \"POST\"\r\n");
      out.write("         ,url : \"ajaxjoincategory.action\"\r\n");
      out.write("         ,data : {category_L_Id : $(\"#category_L_Id4\").val()}\r\n");
      out.write("         ,dataType : \"json\"\r\n");
      out.write("         ,success : function(result)\r\n");
      out.write("         {\r\n");
      out.write("            //alert(result);\r\n");
      out.write("            $(\"#category_S_Id4\").children().remove();\r\n");
      out.write("            $(\"#category_S_Id4\").append(\"<option value=\\\"\\\">선택</option>\");\r\n");
      out.write("            \r\n");
      out.write("            for(var i=0; i<result.length; i++)\r\n");
      out.write("            {\r\n");
      out.write("               $(\"#category_S_Id4\").append(\"<option value=\\\"\"+result[i].category_s_id+\"\\\">\"+result[i].s_cat+\"</option>\");\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         ,error : function(e)\r\n");
      out.write("         {\r\n");
      out.write("            alert(e.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      \r\n");
      out.write("       });\r\n");
      out.write("   \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   // 카테고리 대분류 → 소분류 선택 - 5\r\n");
      out.write("   $(\"#category_L_Id5\").change(function()\r\n");
      out.write("   {\r\n");
      out.write("      $.ajax(\r\n");
      out.write("      {\r\n");
      out.write("         type : \"POST\"\r\n");
      out.write("         ,url : \"ajaxjoincategory.action\"\r\n");
      out.write("         ,data : {category_L_Id : $(\"#category_L_Id5\").val()}\r\n");
      out.write("         ,dataType : \"json\"\r\n");
      out.write("         ,success : function(result)\r\n");
      out.write("         {\r\n");
      out.write("            //alert(result);\r\n");
      out.write("            $(\"#category_S_Id5\").children().remove();\r\n");
      out.write("            $(\"#category_S_Id5\").append(\"<option value=\\\"\\\">선택</option>\");\r\n");
      out.write("            \r\n");
      out.write("            for(var i=0; i<result.length; i++)\r\n");
      out.write("            {\r\n");
      out.write("               $(\"#category_S_Id5\").append(\"<option value=\\\"\"+result[i].category_s_id+\"\\\">\"+result[i].s_cat+\"</option>\");\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         ,error : function(e)\r\n");
      out.write("         {\r\n");
      out.write("            alert(e.responseText);\r\n");
      out.write("         }\r\n");
      out.write("      \r\n");
      out.write("       });\r\n");
      out.write("   \r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function isPassword(asValue) {\r\n");
      out.write("    \r\n");
      out.write("    var regExp = /^(?=.*[a-zA-z])(?=.*[0-9])(?=.*[$`~!@$!%*#^?&\\\\(\\\\)\\-_=+]).{8,16}$/;\r\n");
      out.write("    return regExp.test(asValue); // 형식에 맞는 경우 true 리턴\r\n");
      out.write("    \r\n");
      out.write(" }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- \r\n");
      out.write(" - 회원가입하기 페이지\r\n");
      out.write(" -->\r\n");
      out.write("<div>\r\n");
      out.write("<!-- nav 영역 -->\r\n");
      out.write("<div>\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"subheader\">\r\n");
      out.write("      <p>B:CLE</p>\r\n");
      out.write("      <p class=\"title\">회원가입 하기</p>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"outer\">\r\n");
      out.write("   <!-- <div class=\"inner\"> -->\r\n");
      out.write("      <div class=\"row register-form\">\r\n");
      out.write("      <form action=\"join.action\" method=\"post\" id=\"joinForm\" enctype=\"multipart/form-data\">\r\n");
      out.write("         <p id=\"err\" style=\"color: red; font-size: small;\">* 는 필수 입력사항 입니다.</p><br>\r\n");
      out.write("         <div class=\"form-group col-md-12 col-sm-12\">  \r\n");
      out.write("            프로필 사진*<br>\r\n");
      out.write("            <input type=\"file\" id=\"file\" name=\"url\" value=\"등록\" required=\"required\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <br>\r\n");
      out.write("         <div class=\"form-group col-md-6 col-sm-6\">\r\n");
      out.write("            <label for=\"name\">이름*</label>\r\n");
      out.write("            <input type=\"text\" id=\"name\" name=\"name\" placeholder=\"이름을 입력하세요.\" required=\"required\" class=\"form-control\"/>\r\n");
      out.write("            <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">이름을 입력해주세요.</span><br> -->\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"id form-group col-md-6 col-sm-6\">\r\n");
      out.write("            <label for=\"userId\">아이디*\r\n");
      out.write("               <input type=\"text\" id=\"userId\" name=\"userId\" placeholder=\"아이디를 입력하세요.\" required=\"required\" class=\"input_id form-control\"/>\r\n");
      out.write("               <!-- <input type=\"button\" value=\"중복확인\" id=\"check\"> -->\r\n");
      out.write("               <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">아이디를 입력해주세요.</span><br> -->\r\n");
      out.write("               <span id=checkId  style=\"font-size: small;\"></span><br>\r\n");
      out.write("            </label>\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- 변경 -->\r\n");
      out.write("            <div class=\"form-group col-md-12 col-sm-12\">\r\n");
      out.write("               <label for=\"email\">이메일*</label>\r\n");
      out.write("               <input type=\"email\" name=\"email\" id=\"emailText\" placeholder=\"이메일을 입력하세요.\" required=\"required\" class=\"form-control\"/>\r\n");
      out.write("               <span id=\"e_msg\" style=\"display: none; color: red; font-size: small;\"></span><br>\r\n");
      out.write("              <!--  <button id=\"emailCheck\" onclick=\"emailSend()\">인증코드 보내기</button><br>\r\n");
      out.write("               <input type=\"text\" id=\"certificationNumber\" placeholder=\"인증코드를 입력하세요.\" class=\"form-control\">\r\n");
      out.write("               <button id=\"certificationBtn\" onclick=\"emailCertification()\">인증하기</button>\r\n");
      out.write("               <span id=\"err\" style=\"display: none; color: red; font-size: small;\">인증코드가 일치하지 않습니다.</span><br> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 변경 -->\r\n");
      out.write("            <div class=\"form-group col-md-12 col-sm-12\">\r\n");
      out.write("               <label for=\"pwd\">비밀번호 확인</label>&nbsp;\r\n");
      out.write("               <input type=\"password\" id=\"pwd\" name=\"pwd\" placeholder=\"패스워드를 입력하세요.\" required=\"required\" class=\"form-control\"/>\r\n");
      out.write("               <span id=\"err\" style=\"display: none; color: red; font-size: small;\">비밀번호를 입력해주세요.</span><br>\r\n");
      out.write("               <span id=\"p_msg1\" style=\"display: none; color: green; font-size: small;\"></span><br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 변경 -->\r\n");
      out.write("            <div class=\"form-group col-md-12 col-sm-12\">\r\n");
      out.write("               <label for=\"pwd2\">비밀번호 재확인*</label>\r\n");
      out.write("               <input type=\"password\" id=\"pwd2\" placeholder=\"패스워드를 다시 입력하세요.\" required=\"required\" class=\"form-control\"/>\r\n");
      out.write("               <!-- <span>안녕하세요</span> -->\r\n");
      out.write("               <span id=\"err\" style=\"display: none; color: red; font-size: small;\">비밀번호를 한번 더입력해주세요.</span><br>\r\n");
      out.write("               <span id=\"p_msg2\" style=\"display: none; color: green; font-size: small;\"></span><br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group col-md-12 col-sm-12\">\r\n");
      out.write("               <label for=\"ssn1\">주민번호*</label>\r\n");
      out.write("               <input type=\"text\" id=\"ssn1\" name=\"ssn1\" required=\"required\"> - <input type=\"password\" id=\"ssn2\" name=\"ssn2\" required=\"required\">\r\n");
      out.write("               <span id=\"s_msg\" style=\"display: none; color: red; font-size: small;\"></span><br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group col-md-12 col-sm-12\">\r\n");
      out.write("               <label for=\"tel1\">연락처*</label>\r\n");
      out.write("               <input type=\"tel\" id=\"tel1\" name=\"tel\" required=\"required\" style=\"width: 100px\"><br>\r\n");
      out.write("               <span id=\"err\" style=\"display: none; color: red; font-size: small;\">전화번호를 입력해주세요.</span>\r\n");
      out.write("               <span id=\"t_msg\" style=\"display: none; color: green; font-size: small;\"></span><br>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"form-group col-md-6 col-sm-6\">\r\n");
      out.write("            <label for=\"nickName\">닉네임*</label>\r\n");
      out.write("            <input type=\"text\" id=\"nickName\" name=\"nickName\" placeholder=\"ex) 행복한비클\" required=\"required\" class=\"input_nickname form-control\">\r\n");
      out.write("            <!-- <input type=\"button\" value=\"중복확인\"> -->\r\n");
      out.write("            <!-- <input type=\"button\" value=\"랜덤생성\"> -->\r\n");
      out.write("            <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">닉네임을 입력해주세요.</span><br> -->\r\n");
      out.write("            <span id=checkNickName  style=\"font-size: small;\"></span><br>\r\n");
      out.write("         </div>\r\n");
      out.write("         <br>\r\n");
      out.write("         <div class=\"form-group col-md-6 col-sm-6\">\r\n");
      out.write("            <label for=\"nickName\">첫 번째 지역설정</label>\r\n");
      out.write("            <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">지역은 최소 1개 설정해야합니다.</span><br> -->\r\n");
      out.write("            시*\r\n");
      out.write("            <select name=\"region_L_Id1\" id=\"region_L_Id1\" required=\"required\" class=\"form-control\">\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("            군·구*\r\n");
      out.write("            <select name=\"region_S_Id1\" id=\"region_S_Id1\" required=\"required\" class=\"form-control\">\r\n");
      out.write("               <option value=\"-1\">군·구 단위</option>\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <!-- <input type=\"text\" id=\"regionS1\" placeholder=\"지역1\" required=\"required\"> -->\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"form-group col-md-6 col-sm-6\">\r\n");
      out.write("            <label for=\"nickName\">두 번째 지역설정</label>\r\n");
      out.write("            <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">지역은 최소 1개 설정해야합니다.</span><br> -->\r\n");
      out.write("            시\r\n");
      out.write("            <select name=\"region_L_Id2\" id=\"region_L_Id2\" required=\"required\" class=\"form-control\">\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("            군·구\r\n");
      out.write("            <select name=\"region_S_Id2\" id=\"region_S_Id2\" required=\"required\" class=\"form-control\">\r\n");
      out.write("               <option value=\"-1\">군·구 단위</option>\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <!-- <input type=\"text\" id=\"regionS2\" placeholder=\"지역2\"> -->\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"form-group col-md-6 col-sm-6\">\r\n");
      out.write("            <label for=\"nickName\">세 번째 지역설정</label>\r\n");
      out.write("            <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">지역은 최소 1개 설정해야합니다.</span><br> -->\r\n");
      out.write("            시\r\n");
      out.write("            <select name=\"region_L_Id3\" id=\"region_L_Id3\" required=\"required\" class=\"form-control\">\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("            군·구\r\n");
      out.write("            <select name=\"region_S_Id3\" id=\"region_S_Id3\" required=\"required\" class=\"form-control\">\r\n");
      out.write("               <option value=\"-1\">군·구 단위</option>\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <!-- <input type=\"text\" id=\"regionS3\" placeholder=\"지역3\"> -->\r\n");
      out.write("         </div>\r\n");
      out.write("         <br>\r\n");
      out.write("         <div class=\"form-group col-md-6 col-sm-6\">\r\n");
      out.write("            <label for=\"category\">첫 번째 관심 카테고리*</label>\r\n");
      out.write("            <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">관심카테고리는 최소 1개 설정해야합니다.</span><br> -->\r\n");
      out.write("            <select name=\"category_L_Id1\" id=\"category_L_Id1\" required=\"required\" class=\"form-control\">\r\n");
      out.write("               <option value=\"\">카테고리 선택</option>\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <select name=\"category_S_Id1\" id=\"category_S_Id1\" required=\"required\" class=\"form-control\">\r\n");
      out.write("               <option value=\"-1\">카테고리 상세선택</option>\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <!-- <input type=\"text\" id=\"category1\" placeholder=\"카테고리1\" required=\"required\"> -->\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"form-group col-md-6 col-sm-6\">\r\n");
      out.write("            <label for=\"category\">두 번째 관심 카테고리</label>\r\n");
      out.write("            <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">관심카테고리는 최소 1개 설정해야합니다.</span><br> -->\r\n");
      out.write("            <select name=\"category_L_Id2\" id=\"category_L_Id2\"  class=\"form-control\">\r\n");
      out.write("               <option value=\"\">카테고리 선택</option>\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <select name=\"category_S_Id2\" id=\"category_S_Id2\" class=\"form-control\">\r\n");
      out.write("               <option value=\"-1\">카테고리 상세선택</option>\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <!-- <input type=\"text\" id=\"category2\" placeholder=\"카테고리2\"> -->\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"form-group col-md-6 col-sm-6\">\r\n");
      out.write("            <label for=\"category\">세 번째 관심 카테고리</label>\r\n");
      out.write("            <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">관심카테고리는 최소 1개 설정해야합니다.</span><br> -->\r\n");
      out.write("            <select name=\"category_L_Id3\" id=\"category_L_Id3\"  class=\"form-control\">\r\n");
      out.write("               <option value=\"\">카테고리 선택</option>\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fforEach_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <select name=\"category_S_Id3\" id=\"category_S_Id3\" class=\"form-control\">\r\n");
      out.write("               <option value=\"-1\">카테고리 상세선택</option>\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <!-- <input type=\"text\" id=\"category3\" placeholder=\"카테고리3\"> -->\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"form-group col-md-6 col-sm-6\">\r\n");
      out.write("            <label for=\"category\">네 번째 관심 카테고리</label>\r\n");
      out.write("            <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">관심카테고리는 최소 1개 설정해야합니다.</span><br> -->\r\n");
      out.write("            <select name=\"category_L_Id4\" id=\"category_L_Id4\"  class=\"form-control\">\r\n");
      out.write("               <option value=\"\">카테고리 선택</option>\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fforEach_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <select name=\"category_S_Id4\" id=\"category_S_Id4\" class=\"form-control\">\r\n");
      out.write("               <option value=\"-1\">카테고리 상세선택</option>\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <!-- <input type=\"text\" id=\"category4\" placeholder=\"카테고리4\"> -->\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"form-group col-md-6 col-sm-6\">\r\n");
      out.write("            <label for=\"category\">다섯 번째 관심 카테고리</label>\r\n");
      out.write("            <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">관심카테고리는 최소 1개 설정해야합니다.</span><br> -->\r\n");
      out.write("            <select name=\"category_L_Id5\" id=\"category_L_Id5\" class=\"form-control\">\r\n");
      out.write("               <option value=\"\">카테고리 선택</option>\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fforEach_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <select name=\"category_S_Id5\" id=\"category_S_Id5\" class=\"form-control\">\r\n");
      out.write("               <option value=\"-1\">카테고리 상세선택</option>\r\n");
      out.write("            </select><br>\r\n");
      out.write("            <!-- <input type=\"text\" id=\"category5\" placeholder=\"카테고리5\"> -->\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"form-group col-md-12 col-sm-12\" style=\"text-align: center;\">\r\n");
      out.write("            <!-- <span id=\"err\" style=\"display: none; color: red; font-size: small;\">회원가입의 항목들을 모두 입력해주세요.</span><br> -->\r\n");
      out.write("            <input type=\"button\" value=\"가입하기\" id=\"submitBtn\" class=\"btn btn-warning\">\r\n");
      out.write("            <!-- <input type=\"reset\" value=\"모두 지우기\" class=\"btn btn-warning\"> -->\r\n");
      out.write("            <input type=\"button\" value=\"취소\" class=\"btn btn-warning\"\r\n");
      out.write("            onclick=\"javascript:location.href='");
      out.print(cp);
      out.write("/loginpage.action'\">\r\n");
      out.write("         </div>\r\n");
      out.write("      </form>\r\n");
      out.write("      </div>\r\n");
      out.write("   <!-- </div> -->\r\n");
      out.write("   \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/view/Join.jsp(747,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("subHeader.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/view/Join.jsp(829,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("region");
      // /WEB-INF/view/Join.jsp(829,15) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regionLList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                       <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.region_l_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.city }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/view/Join.jsp(844,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("region");
      // /WEB-INF/view/Join.jsp(844,15) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regionLList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                       <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.region_l_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.city }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/view/Join.jsp(859,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("region");
      // /WEB-INF/view/Join.jsp(859,15) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regionLList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                       <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.region_l_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.city }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /WEB-INF/view/Join.jsp(875,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("category");
      // /WEB-INF/view/Join.jsp(875,15) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryLList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                       <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.category_l_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.l_cat }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent(null);
      // /WEB-INF/view/Join.jsp(889,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVar("category");
      // /WEB-INF/view/Join.jsp(889,15) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryLList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                       <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.category_l_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.l_cat }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f5_reused = false;
    try {
      _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f5.setParent(null);
      // /WEB-INF/view/Join.jsp(903,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setVar("category");
      // /WEB-INF/view/Join.jsp(903,15) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryLList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
        if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                       <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.category_l_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.l_cat }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f5);
      _jspx_th_c_005fforEach_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f6 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f6_reused = false;
    try {
      _jspx_th_c_005fforEach_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f6.setParent(null);
      // /WEB-INF/view/Join.jsp(917,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f6.setVar("category");
      // /WEB-INF/view/Join.jsp(917,15) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f6.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryLList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f6 = _jspx_th_c_005fforEach_005f6.doStartTag();
        if (_jspx_eval_c_005fforEach_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                       <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.category_l_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.l_cat }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f6.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f6);
      _jspx_th_c_005fforEach_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f7 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f7_reused = false;
    try {
      _jspx_th_c_005fforEach_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f7.setParent(null);
      // /WEB-INF/view/Join.jsp(931,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f7.setVar("category");
      // /WEB-INF/view/Join.jsp(931,15) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f7.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryLList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f7 = _jspx_th_c_005fforEach_005f7.doStartTag();
        if (_jspx_eval_c_005fforEach_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                       <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.category_l_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.l_cat }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f7.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f7);
      _jspx_th_c_005fforEach_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/view/Join.jsp(955,6) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
